/**
 * Card content for loading view life animation.
 */
export const cards = [
    {year: "1998", anecdote: "the journey begins."},
    {year: "1999", anecdote: "first steps."},
    {year: "2000", anecdote: "new millennium."},
    {year: "2001", anecdote: "off to Kindergarten."},
    {year: "2002", anecdote: "played piano on the street."},
    {year: "2003", anecdote: "rode on a police bike."},
    {year: "2004", anecdote: "off to school."},
    {year: "2005", anecdote: "ran around parking lots."},
    {year: "2006", anecdote: "became football captain."},
    {year: "2007", anecdote: "swimming is fun."},
    {year: "2008", anecdote: "and more school."},
    {year: "2009", anecdote: "avoided fainting in front of the pyramids."},
    {year: "2010", anecdote: "wrote my first lines of code."},
    {year: "2012", anecdote: "did some chemistry."},
    {year: "2012", anecdote: "discovered my love for techno music."},
    {year: "2013", anecdote: "learned to windsurf."},
    {year: "2014", anecdote: "explored Turkey."},
    {year: "2015", anecdote: "vacation time."},
    {year: "2016", anecdote: "moved to Munich."},
    {year: "2017", anecdote: "first rave."},
    {year: "2018", anecdote: "first solo vacation."},
    {year: "2019", anecdote: "covid hit."},
    {year: "2020", anecdote: "grew a beard."},
    {year: "2021", anecdote: "graduated B.Sc."},
    {year: "2022", anecdote: "moved to Paris and back."},
];
